### ISSUE TITLE
absolute pressure and relative pressure still mixed up at some places

### ISSUE THREAD

**Issue by wega52** [adlerweb/ESP8266-BME280-Multi#1]
Line 249 should read
float pressure_r = bme.seaLevelForAltitude(ALTITUDE, pressure);

Line 410  should read
float pressure = bme.readPressure() / 100.0F;

Line 420 ff  should read
  out += "g/m3\nRelative Pressure: ";
  out += bme.seaLevelForAltitude(ALTITUDE, pressure);
  out += "hPa\nAbsolute Pressure: ";
  out += pressure;

**Comment by Schilly71** [comment]
Hello,
Thank you for your error detection. I had seen your hint late. I always had a "0" in relative humidity when the data was transferred to census. 
@adlerweb : Wouldn't it be a good idea to update your changes in the code?

Refards,
Schilly

**Comment by adlerweb** [comment]
Oops - pretty sure I edited it after this report, but guess I never commited the changes m(. Thanks for the heads up.
